source ~/.bash/my.sh
source ~/.bash/bundler.sh
source ~/.bash/git.sh
source ~/.bash/gnu-sed.sh
source ~/.bash/go.sh
source ~/.bash/oracle.sh
source ~/.bash/postgres.sh
source ~/.bash/rails.sh
source ~/.bash/rbenv.sh
source ~/.bash/ruby.sh
source ~/.bash/rspec.sh
source ~/.bash/aliases.sh
