(el-get-bundle elpa:feature-mode)
(el-get-bundle elpa:git-gutter)
(el-get-bundle elpa:haml-mode)
(el-get-bundle elpa:markdown-mode)
(el-get-bundle elpa:migemo)
(el-get-bundle elpa:sass-mode)
(el-get-bundle elpa:yaml-mode)

(el-get-bundle ace-isearch)
(el-get-bundle ag)
(el-get-bundle anzu)
(el-get-bundle auto-complete)
(el-get-bundle coffee-mode)
(el-get-bundle git-commit-mode)
(el-get-bundle helm)
(el-get-bundle helm-ag)
(el-get-bundle helm-ls-git)
(el-get-bundle helm-swoop)
(el-get-bundle projectile-rails)
(el-get-bundle rspec-mode)
(el-get-bundle sync-recentf)

(el-get-bundle tarao/el-get-lock)

(el-get-lock)
