(el-get-bundle elpa:feature-mode)
(el-get-bundle elpa:haml-mode)
(el-get-bundle elpa:markdown-mode)
(el-get-bundle elpa:migemo)
(el-get-bundle elpa:sass-mode)
(el-get-bundle elpa:yaml-mode)

(el-get-bundle auto-complete)
(el-get-bundle helm)
(el-get-bundle projectile-rails)
